#wip

name: Docker Build

on:
  release:
    types: [created]
jobs:

  docker-build:
    runs-on: ubuntu-latest

    needs: maven-build  # Aguarda a conclusão do job 'maven-build' antes de executar este job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_TOKEN}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yourdockerhubusername/yourimagename:latest
      - run: echo "This job's status is ${{ job.status }}."